# This is a config for E2B sandbox template.
# You can use template ID (1346tuyyoohiyu0wz6a5) or template name (web-gen-t3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("web-gen-t3") # Sync sandbox
# sandbox = await AsyncSandbox.create("web-gen-t3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('web-gen-t3')

team_id = "fa81d937-c610-4d49-9942-e7ed6f4743fa"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "web-gen-t3"
template_id = "1346tuyyoohiyu0wz6a5"
